DATA_URL:
  SMALL_URL: https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
  FULL_URL: https://files.grouplens.org/datasets/movielens/ml-latest.zip

DATA_DIR:
  DATA_100K:
    NAME: ml-latest.zip
    RAW: data/100k/raw/
    TRAIN: data/100k/train/ratings.csv
    TEST: data/100k/test/ratings.csv
    EVAL: data/100k/eval/ratings.csv
    SPLITS: [0.7, 0.15, 0.15]
    N_USERS: 610
    N_MOVIES: 9724

  DATA_10M:
    RAW: data/10M/raw/
    TRAIN: data/10M/train/ratings.csv
    TEST: data/10M/test/ratings.csv
    EVAL: data/10M/eval/ratings.csv
    SPLITS: [0.8, 0.1, 0.1]
    N_USERS: 330975
    N_MOVIES: 86000

