# Default values for dataset configuration
AUTOENCODER_DATASET_CONFIG:
  split_mode: random
  data_size: 100K
  batch_size: 32
  num_workers: 2

USER_ITEM_DATASET_CONFIG:
  split_mode: user
  data_size: 100K
  negative_sampling: False
  testing: True
  batch_size: 512
  num_workers: 2